name: Vader Tests

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rhysd/action-setup-vim@v1
      - run: ./test/run-tests.sh
